# Generated by Django 4.2.10 on 2024-03-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unidashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidetail", options={"verbose_name_plural": "University Details"},
        ),
    ]
