# Generated by Django 4.2.10 on 2024-03-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentdashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserPost",),
    ]
