# Generated by Django 4.2.10 on 2024-02-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_user_type"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
