# Generated by Django 4.2.10 on 2024-03-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0006_profile_college_profile_country_profile_first_course_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="degree_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bachelor", "Bachelor"),
                    ("master", "Master"),
                    ("phd", "PhD"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
