# Generated by Django 4.2.10 on 2024-03-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_profile_degree_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="bio",),
    ]
