# Generated by Django 4.2.10 on 2024-03-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserQuery", new_name="ContactForm",),
    ]
